services:

  alloy:
    image: grafana/alloy:latest
    ports:
      - "4317:4317"
      - "4318:4318"
      - "12345:12345"
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    command: run /etc/alloy/config.alloy --server.http.listen-addr=0.0.0.0:12345 --stability.level=public-preview
    env_file: .env
    restart: unless-stopped

  account-service:
    build: ./account-service
    ports: ["8080:8080"]
    environment:
      OTEL_SERVICE_NAME: account-service
      OTEL_RESOURCE_ATTRIBUTES: service.namespace=banking-poc
      OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_LOGS_EXPORTER: none
      OTEL_METRICS_EXPORTER: otlp
      OTEL_TRACES_EXPORTER: otlp
      OTEL_INSTRUMENTATION_COMMON_EXCLUDED_URLS: /actuator/*
      BALANCE_SERVICE_URL: http://balance-service:8081
      NOTIFICATION_SERVICE_URL: http://notification-service:8082
    depends_on: [alloy, balance-service, notification-service]

  balance-service:
    build: ./balance-service
    ports: ["8081:8081"]
    environment:
      OTEL_SERVICE_NAME: balance-service
      OTEL_RESOURCE_ATTRIBUTES: service.namespace=banking-poc
      OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_LOGS_EXPORTER: none
      OTEL_METRICS_EXPORTER: otlp
      OTEL_TRACES_EXPORTER: otlp
      OTEL_INSTRUMENTATION_COMMON_EXCLUDED_URLS: /actuator/*
    depends_on: [alloy]

  notification-service:
    build: ./notification-service
    ports: ["8082:8082"]
    environment:
      OTEL_SERVICE_NAME: notification-service
      OTEL_RESOURCE_ATTRIBUTES: service.namespace=banking-poc
      OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_LOGS_EXPORTER: none
      OTEL_METRICS_EXPORTER: otlp
      OTEL_TRACES_EXPORTER: otlp
      OTEL_INSTRUMENTATION_COMMON_EXCLUDED_URLS: /actuator/*
    depends_on: [alloy]

  load-generator:
    build: ./load-generator
    ports: ["8090:8090"]
    environment:
      OTEL_SERVICE_NAME: load-generator
      OTEL_RESOURCE_ATTRIBUTES: service.namespace=banking-poc
      OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_LOGS_EXPORTER: none
      OTEL_METRICS_EXPORTER: otlp
      OTEL_TRACES_EXPORTER: otlp
      ORDER_SERVICE_URL: http://account-service:8080
      OTEL_INSTRUMENTATION_COMMON_EXCLUDED_URLS: /actuator/*
    depends_on: [alloy, account-service]

  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    depends_on: [account-service, balance-service]

