apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banking-poc

resources:
  - namespace.yaml
  - alloy.yaml
  - account-service.yaml
  - balance-service.yaml
  - notification-service.yaml
  - load-generator.yaml
  - frontend.yaml

configMapGenerator:
  - name: alloy-config
    files:
      - config.alloy=alloy/config.alloy

generatorOptions:
  disableNameSuffixHash: true